import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import HomeButton from "@/components/HomeButton";

const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HomeButton />
        {children}
      </body>
    </html>
  );
}
